modLoader="javafml" #mandatory
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="DSMSL (DON'T SNATCH MA STUFF LICENSE)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="drippyloadingscreen" #mandatory
version="1.5.0" #mandatory
displayName="Drippy Loading Screen" #mandatory
authors="Keksuccino" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen" #optional
description='''Damn, what a drippy loading screen!

COPYRIGHT:

> Drippy Loading Screen © Copyright 2021 Keksuccino.
  Drippy Loading Screen is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
  See https://github.com/Keksuccino/Drippy-Loading-Screen/blob/main/LICENSE.md for more information about this license.'''

[[dependencies.drippyloadingscreen]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.3.3,)"
side="BOTH"

[[dependencies.drippyloadingscreen]]
modId="fancymenu"
mandatory=false
ordering="AFTER"
versionRange="[2.2.1,)"
side="BOTH"

[[dependencies.drippyloadingscreen]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="CLIENT"

[[dependencies.drippyloadingscreen]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="CLIENT"