modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
clientSideOnly=false
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}" #optional
#If mod is present on server, only let users with same client-side mod version join
displayTest="MATCH_VERSION"
description='''Damn, what a drippy loading screen!

COPYRIGHT:

> Drippy Loading Screen © Copyright 2021-2023 Keksuccino.
  Drippy Loading Screen is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
  See https://github.com/Keksuccino/Drippy-Loading-Screen/blob/main/LICENSE.md for more information about this license.'''

[[dependencies.${mod_id}]]
    modId="konkrete"
    mandatory=true
    ordering="NONE"
    versionRange="[1.6.1,)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fancymenu"
    mandatory=true
    ordering="AFTER"
    versionRange="[2.14.9,3.0.0)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
