modLoader="javafml" #mandatory
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="KML (Keksuccino Mod License)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="drippyloadingscreen" #mandatory
version="1.1.0" #mandatory
displayName="Drippy Loading Screen" #mandatory
authors="Keksuccino" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/drippyloadingscreen" #optional
description='''Damn, what a drippy loading screen!

COPYRIGHT:

> Drippy Loading Screen © Copyright 2021 Keksuccino.
  Drippy Loading Screen is licensed under KML.
  See https://github.com/Keksuccino/DrippyLoadingScreen/blob/main/LICENSE.md for more infos about this license.'''

[[dependencies.drippyloadingscreen]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.1.6,)"
side="BOTH"

[[dependencies.drippyloadingscreen]]
modId="fancymenu"
mandatory=false
ordering="AFTER"
versionRange="[2.2.1,)"
side="BOTH"