package de.keksuccino.drippyloadingscreen.earlywindow.window.config;

/**
 * Immutable view of the subset of Drippy options that are relevant for the early loading window.
 */
public record EarlyLoadingOptions(
        String backgroundTexturePath,
        boolean backgroundPreserveAspectRatio,
        String logoTexturePath,
        int logoWidth,
        int logoHeight,
        int logoOffsetX,
        int logoOffsetY,
        String windowTitle,
        String barBackgroundTexturePath,
        String barProgressTexturePath,
        int barWidth,
        int barHeight,
        int barOffsetX,
        int barOffsetY,
        int windowWidthOverride,
        int windowHeightOverride,
        boolean hideLogo,
        boolean hideBar,
        boolean hideLogger,
        String topLeftWatermarkTexturePath,
        int topLeftWatermarkWidth,
        int topLeftWatermarkHeight,
        int topLeftWatermarkOffsetX,
        int topLeftWatermarkOffsetY,
        String topRightWatermarkTexturePath,
        int topRightWatermarkWidth,
        int topRightWatermarkHeight,
        int topRightWatermarkOffsetX,
        int topRightWatermarkOffsetY,
        String bottomLeftWatermarkTexturePath,
        int bottomLeftWatermarkWidth,
        int bottomLeftWatermarkHeight,
        int bottomLeftWatermarkOffsetX,
        int bottomLeftWatermarkOffsetY,
        String bottomRightWatermarkTexturePath,
        int bottomRightWatermarkWidth,
        int bottomRightWatermarkHeight,
        int bottomRightWatermarkOffsetX,
        int bottomRightWatermarkOffsetY
) {

    public static EarlyLoadingOptions defaults() {
        return new EarlyLoadingOptions(
                null,
                true,
                null,
                480,
                120,
                0,
                -50,
                "Minecraft",
                null,
                null,
                400,
                40,
                0,
                50,
                -1,
                -1,
                false,
                false,
                false,
                null,
                100,
                100,
                0,
                0,
                null,
                100,
                100,
                0,
                0,
                null,
                100,
                100,
                0,
                0,
                null,
                100,
                100,
                0,
                0
        );
    }
}
